version: '3.8'

services:
  api:
    container_name: dockerdev
    build:
      context: ./
#      dockerfile: Dockerfile.debug
      dockerfile: Dockerfile.gql_service
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - "3200:3200"
      - "40000:40000"
    env_file:
      - .env
    volumes:
#      - .:/dockerdev
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
