// Code generated by ent, DO NOT EDIT.

package transactionsync

import (
	"time"
)

const (
	// Label holds the string label denoting the transactionsync type in the database.
	Label = "transaction_sync"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCursor holds the string denoting the cursor field in the database.
	FieldCursor = "cursor"
	// EdgeItem holds the string denoting the item edge name in mutations.
	EdgeItem = "item"
	// Table holds the table name of the transactionsync in the database.
	Table = "transaction_syncs"
	// ItemTable is the table that holds the item relation/edge.
	ItemTable = "transaction_syncs"
	// ItemInverseTable is the table name for the PlaidItem entity.
	// It exists in this package in order to avoid circular dependency with the "plaiditem" package.
	ItemInverseTable = "plaid_items"
	// ItemColumn is the table column denoting the item relation/edge.
	ItemColumn = "plaid_item_transaction_syncs"
)

// Columns holds all SQL columns for transactionsync fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldCursor,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "transaction_syncs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"plaid_item_transaction_syncs",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// CursorValidator is a validator for the "cursor" field. It is called by the builders before save.
	CursorValidator func(string) error
)
