// Code generated by ent, DO NOT EDIT.

package transactionsync

import (
	"time"
	"wallit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldEQ(FieldCreatedAt, v))
}

// Cursor applies equality check predicate on the "cursor" field. It's identical to CursorEQ.
func Cursor(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldEQ(FieldCursor, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldLTE(FieldCreatedAt, v))
}

// CursorEQ applies the EQ predicate on the "cursor" field.
func CursorEQ(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldEQ(FieldCursor, v))
}

// CursorNEQ applies the NEQ predicate on the "cursor" field.
func CursorNEQ(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldNEQ(FieldCursor, v))
}

// CursorIn applies the In predicate on the "cursor" field.
func CursorIn(vs ...string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldIn(FieldCursor, vs...))
}

// CursorNotIn applies the NotIn predicate on the "cursor" field.
func CursorNotIn(vs ...string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldNotIn(FieldCursor, vs...))
}

// CursorGT applies the GT predicate on the "cursor" field.
func CursorGT(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldGT(FieldCursor, v))
}

// CursorGTE applies the GTE predicate on the "cursor" field.
func CursorGTE(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldGTE(FieldCursor, v))
}

// CursorLT applies the LT predicate on the "cursor" field.
func CursorLT(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldLT(FieldCursor, v))
}

// CursorLTE applies the LTE predicate on the "cursor" field.
func CursorLTE(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldLTE(FieldCursor, v))
}

// CursorContains applies the Contains predicate on the "cursor" field.
func CursorContains(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldContains(FieldCursor, v))
}

// CursorHasPrefix applies the HasPrefix predicate on the "cursor" field.
func CursorHasPrefix(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldHasPrefix(FieldCursor, v))
}

// CursorHasSuffix applies the HasSuffix predicate on the "cursor" field.
func CursorHasSuffix(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldHasSuffix(FieldCursor, v))
}

// CursorEqualFold applies the EqualFold predicate on the "cursor" field.
func CursorEqualFold(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldEqualFold(FieldCursor, v))
}

// CursorContainsFold applies the ContainsFold predicate on the "cursor" field.
func CursorContainsFold(v string) predicate.TransactionSync {
	return predicate.TransactionSync(sql.FieldContainsFold(FieldCursor, v))
}

// HasItem applies the HasEdge predicate on the "item" edge.
func HasItem() predicate.TransactionSync {
	return predicate.TransactionSync(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemWith applies the HasEdge predicate on the "item" edge with a given conditions (other predicates).
func HasItemWith(preds ...predicate.PlaidItem) predicate.TransactionSync {
	return predicate.TransactionSync(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ItemInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ItemTable, ItemColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TransactionSync) predicate.TransactionSync {
	return predicate.TransactionSync(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TransactionSync) predicate.TransactionSync {
	return predicate.TransactionSync(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TransactionSync) predicate.TransactionSync {
	return predicate.TransactionSync(func(s *sql.Selector) {
		p(s.Not())
	})
}
