// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"wallit/ent/predicate"
	"wallit/ent/transactionsync"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TransactionSyncDelete is the builder for deleting a TransactionSync entity.
type TransactionSyncDelete struct {
	config
	hooks    []Hook
	mutation *TransactionSyncMutation
}

// Where appends a list predicates to the TransactionSyncDelete builder.
func (tsd *TransactionSyncDelete) Where(ps ...predicate.TransactionSync) *TransactionSyncDelete {
	tsd.mutation.Where(ps...)
	return tsd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tsd *TransactionSyncDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, TransactionSyncMutation](ctx, tsd.sqlExec, tsd.mutation, tsd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tsd *TransactionSyncDelete) ExecX(ctx context.Context) int {
	n, err := tsd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tsd *TransactionSyncDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: transactionsync.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: transactionsync.FieldID,
			},
		},
	}
	if ps := tsd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tsd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tsd.mutation.done = true
	return affected, err
}

// TransactionSyncDeleteOne is the builder for deleting a single TransactionSync entity.
type TransactionSyncDeleteOne struct {
	tsd *TransactionSyncDelete
}

// Where appends a list predicates to the TransactionSyncDelete builder.
func (tsdo *TransactionSyncDeleteOne) Where(ps ...predicate.TransactionSync) *TransactionSyncDeleteOne {
	tsdo.tsd.mutation.Where(ps...)
	return tsdo
}

// Exec executes the deletion query.
func (tsdo *TransactionSyncDeleteOne) Exec(ctx context.Context) error {
	n, err := tsdo.tsd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{transactionsync.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tsdo *TransactionSyncDeleteOne) ExecX(ctx context.Context) {
	if err := tsdo.Exec(ctx); err != nil {
		panic(err)
	}
}
