// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DiscountOffer is the predicate function for discountoffer builders.
type DiscountOffer func(*sql.Selector)

// Merchant is the predicate function for merchant builders.
type Merchant func(*sql.Selector)

// Notification is the predicate function for notification builders.
type Notification func(*sql.Selector)

// PlaidInstitution is the predicate function for plaidinstitution builders.
type PlaidInstitution func(*sql.Selector)

// PlaidInstitutionAccount is the predicate function for plaidinstitutionaccount builders.
type PlaidInstitutionAccount func(*sql.Selector)

// PlaidItem is the predicate function for plaiditem builders.
type PlaidItem func(*sql.Selector)

// SpendingCategory is the predicate function for spendingcategory builders.
type SpendingCategory func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// TransactionSync is the predicate function for transactionsync builders.
type TransactionSync func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserNotificationChannelPreferences is the predicate function for usernotificationchannelpreferences builders.
type UserNotificationChannelPreferences func(*sql.Selector)
